# Generated by Django 3.2.9 on 2023-02-23 16:58

import blog_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodels',
            managers=[
                ('objects', blog_app.models.UserManager()),
            ],
        ),
    ]
