# Generated by Django 3.2.9 on 2023-02-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_usermodels_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('date', models.TimeField(auto_now_add=True)),
                ('categorie', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ActicleModels',
        ),
    ]
