# Generated by Django 3.2.9 on 2023-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20230224_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='categorie',
            field=models.CharField(choices=[('HF', 'Healthy Food'), ('OC', 'Organic Cuisine'), ('VF', 'Vegetarian Food')], max_length=2),
        ),
    ]
