# Generated by Django 3.2.9 on 2023-02-24 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_postmodels_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodels',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
