# Generated by Django 3.2.9 on 2023-02-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_postmodels_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodels',
            name='image',
            field=models.ImageField(null=True, upload_to='vincent_work/projectBlog/blog/blog_app/static/images/posts_images'),
        ),
    ]
