# Generated by Django 3.2.9 on 2023-02-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_postmodels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='image',
            field=models.ImageField(null=True, upload_to='C:/Users/Vincent/Documents/GitHub/Prog_Web/vincent_work/projectBlog/blog/blog_app/static/images/posts_images'),
        ),
    ]
