# Generated by Django 3.2.9 on 2023-02-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_postmodels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/posts_images'),
        ),
    ]
