# Generated by Django 3.2.9 on 2023-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_alter_postmodels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='categorie',
            field=models.CharField(choices=[('Healthy Food', 'Healthy Food'), ('Organic Cuisine', 'Organic Cuisine'), ('Vegetarian Food', 'Vegetarian Food')], max_length=15),
        ),
    ]
