# Generated by Django 3.2.9 on 2023-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_alter_postmodels_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
