# Generated by Django 3.2.9 on 2023-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_alter_postmodels_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
