# Generated by Django 3.2.9 on 2023-03-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_commentmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodels',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.postmodels'),
            preserve_default=False,
        ),
    ]
