# Generated by Django 3.2.9 on 2023-03-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0019_commentmodels_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodels',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
