# Generated by Django 3.2.9 on 2023-03-03 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_alter_commentmodels_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodels',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
    ]
