# Generated by Django 3.2.9 on 2023-03-03 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_commentmodels_favoris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodels',
            name='favoris',
        ),
        migrations.AddField(
            model_name='postmodels',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
    ]
