# Generated by Django 3.2.9 on 2023-03-03 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_auto_20230303_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodels',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
