# Generated by Django 3.2.9 on 2023-03-22 14:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0024_postmodels_testcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
