# Generated by Django 3.2.9 on 2023-03-25 15:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0025_alter_postmodels_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
