# Generated by Django 3.2.9 on 2023-04-02 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0026_alter_postmodels_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='biographie',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
